### ISSUE TITLE
cannot get admin rights

### ISSUE THREAD

**Issue by weikewei110** [SkinSpotlights/CreatorSuite-ReplayAPI#27] opened 2021-05-20 04:09 UTC
running the program with admin,keeps popping up the "tool needs to be ran as admin" dialog box.

**Comment by SkinSpotlights** [comment] 2021-05-21 15:07
What server are you currently trying to use it on?

That error triggers when the tool gets a "Access Denied" response when trying to open the process to get the command line information.

Currently it can triggered by the game being ran by admin when the tool isn't which is the most generic error for this but other things can include, anti-virus blocking the tool, Garena/Chinese Servers run a custom anticheat that block the tool.

If you're on Garena the work around is to close down all the Garena client and League client and then manually launching the replay, Garena Anticheat won't launch with the game then and the tool will be able to work.

I don't know if the Chinese servers will work using the same technique.

**Comment by weikewei110** [comment] 2021-05-23 16:35
hello,I'm not run the game on Gerena,but run Chinese League client with anti-cheat program.i have already close the anti-cheat program. ---- Replied Message ***@***.***>Date05/21/2021 23:07 ***@***.***> ***@***.******@***.***>SubjectRe: [SkinSpotlights/CreatorSuite-ReplayAPI] cannot get admin rights (#27)
What server are you currently trying to use it on?
That error triggers when the tool gets a "Access Denied" response when trying to open the process to get the command line information.
Currently it can triggered by the game being ran by admin when the tool isn't which is the most generic error for this but other things can include, anti-virus blocking the tool, Garena/Chinese Servers run a custom anticheat that block the tool.
If you're on Garena the work around is to close down all the Garena client and League client and then manually launching the replay, Garena Anticheat won't launch with the game then and the tool will be able to work.
I don't know if the Chinese servers will work using the same technique.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/SkinSpotlights/CreatorSuite-ReplayAPI/issues/27#issuecomment-846019209",
"url": "https://github.com/SkinSpotlights/CreatorSuite-ReplayAPI/issues/27#issuecomment-846019209",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by SkinSpotlights** [comment] 2021-05-23 19:18
Then this is a duplicate of error #21 

All I can suggest doing is downloading the NA Game Client and manually launch the replay with that executable as the Tencent one has things that block the tool and I need to find a different way to get the command line reliably or add a toggle in settings to skip that check.

**Closed as completed by SkinSpotlights** 2021-05-23 19:18 UTC
